import { User, CaseItem, EvaluationResult, CourseTask, ScoringCriteria, LearningStats, KnowledgeSource, KnowledgeNode } from './types';

// 模拟用户数据
export const mockUsers: User[] = [
  {
    id: '1',
    username: 'student1',
    password: '123456',
    role: 'student',
    name: '张三',
    email: 'zhangsan@example.com',
    studentId: 'S2024001',
    department: '临床医学院',
  },
  {
    id: '2',
    username: 'student2',
    password: '123456',
    role: 'student',
    name: '李四',
    email: 'lisi@example.com',
    studentId: 'S2024002',
    department: '临床医学院',
  },
  {
    id: '3',
    username: 'teacher1',
    password: '123456',
    role: 'teacher',
    name: '王教授',
    email: 'wangprof@example.com',
    teacherId: 'T001',
    department: '内科',
  },
  {
    id: '4',
    username: 'admin',
    password: 'admin123',
    role: 'admin',
    name: '系统管理员',
    email: 'admin@example.com',
  },
];

// 模拟病例库数据
export const mockCases: CaseItem[] = [
  {
    id: 'case1',
    name: '急性上呼吸道感染',
    department: '内科',
    disease: '上呼吸道感染',
    population: '成人',
    difficulty: 'easy',
    description: '患者主诉发热、咽痛、鼻塞3天',
    symptoms: ['发热', '咽痛', '鼻塞', '流涕', '咳嗽'],
    diagnosis: '急性上呼吸道感染',
    treatment: ['对症治疗', '多休息', '多饮水', '抗病毒药物'],
    aisp: {
      avatar: '👨',
      name: '李明',
      age: 28,
      gender: '男',
      personality: '配合度高，表达清晰',
    },
    status: 'approved',
    createdAt: new Date('2026-01-01'),
    approvedAt: new Date('2026-01-02'),
  },
  {
    id: 'case2',
    name: '儿童支气管炎',
    department: '儿科',
    disease: '支气管炎',
    population: '儿童',
    difficulty: 'medium',
    description: '患儿咳嗽、气促5天，家长代述病情',
    symptoms: ['咳嗽', '气促', '发热', '食欲减退'],
    diagnosis: '急性支气管炎',
    treatment: ['止咳化痰', '抗感染', '雾化治疗', '观察病情'],
    aisp: {
      avatar: '👶',
      name: '小明',
      age: 5,
      gender: '男',
      personality: '表达能力有限，需家长协助',
    },
    status: 'approved',
    createdAt: new Date('2026-01-01'),
    approvedAt: new Date('2026-01-02'),
  },
  {
    id: 'case3',
    name: '老年高血压并发症',
    department: '心内科',
    disease: '高血压',
    population: '老年',
    difficulty: 'hard',
    description: '老年患者，高血压病史20年，近期头晕加重',
    symptoms: ['头晕', '头痛', '心悸', '乏力', '视物模糊'],
    diagnosis: '高血压3级（极高危组）',
    treatment: ['降压药物调整', '监测血压', '低盐饮食', '定期复查'],
    aisp: {
      avatar: '👴',
      name: '张大爷',
      age: 72,
      gender: '男',
      personality: '听力稍差，沟通需耐心',
    },
    status: 'approved',
    createdAt: new Date('2026-01-01'),
    approvedAt: new Date('2026-01-02'),
  },
  {
    id: 'case4',
    name: '急性胃炎',
    department: '消化内科',
    disease: '急性胃炎',
    population: '成人',
    difficulty: 'easy',
    description: '患者饮食不洁后出现腹痛、恶心、呕吐',
    symptoms: ['上腹痛', '恶心', '呕吐', '腹泻', '食欲不振'],
    diagnosis: '急性胃炎',
    treatment: ['禁食水', '抑酸治疗', '补液', '对症处理'],
    aisp: {
      avatar: '👩',
      name: '王丽',
      age: 35,
      gender: '女',
      personality: '表达清晰，情绪焦虑',
    },
    status: 'approved',
    createdAt: new Date('2026-01-01'),
    approvedAt: new Date('2026-01-02'),
  },
  {
    id: 'case5',
    name: '糖尿病酮症酸中毒',
    department: '内分泌科',
    disease: '糖尿病',
    population: '成人',
    difficulty: 'hard',
    description: '糖尿病患者，近期血糖控制不佳，出现意识障碍',
    symptoms: ['意识模糊', '呼吸深快', '恶心呕吐', '腹痛', '多尿'],
    diagnosis: '糖尿病酮症酸中毒',
    treatment: ['胰岛素治疗', '补液', '纠正电解质紊乱', 'ICU监护'],
    aisp: {
      avatar: '👨',
      name: '赵强',
      age: 45,
      gender: '男',
      personality: '意识状态差，沟通困难',
    },
    status: 'approved',
    createdAt: new Date('2026-01-01'),
    approvedAt: new Date('2026-01-02'),
  },
  {
    id: 'case6',
    name: '小儿腹泻',
    department: '儿科',
    disease: '急性腹泻',
    population: '儿童',
    difficulty: 'medium',
    description: '患儿腹泻3天，大便次数增多，水样便',
    symptoms: ['腹泻', '发热', '呕吐', '食欲减退', '精神萎靡'],
    diagnosis: '急性感染性腹泻',
    treatment: ['口服补液盐', '益生菌', '饮食调整', '观察脱水情况'],
    aisp: {
      avatar: '👧',
      name: '小红',
      age: 3,
      gender: '女',
      personality: '哭闹，需要安抚',
    },
    status: 'approved',
    createdAt: new Date('2026-01-01'),
    approvedAt: new Date('2026-01-02'),
  },
];

// 模拟评分记录
export const mockEvaluations: EvaluationResult[] = [
  {
    id: 'eval1',
    studentId: '1',
    caseId: 'case1',
    score: 85,
    communicationScore: 90,
    diagnosisScore: 85,
    treatmentScore: 80,
    feedback: '问诊全面，沟通技巧良好。建议加强对治疗方案的完整性考虑。',
    timestamp: new Date('2026-01-10T10:30:00'),
    duration: 15,
    messages: [
      {
        id: 'm1',
        role: 'aisp',
        content: '您好，医生。我是李明，今年28岁。我感觉不太舒服，头痛、发热已经3天了。',
        type: 'text',
        timestamp: new Date('2026-01-10T10:15:00'),
      },
      {
        id: 'm2',
        role: 'user',
        content: '你好，除了头痛发热，还有其他症状吗？比如咳嗽、流鼻涕？',
        type: 'text',
        timestamp: new Date('2026-01-10T10:15:30'),
      },
      {
        id: 'm3',
        role: 'aisp',
        content: '有的，稍微有点流鼻涕，偶尔咳嗽几声，但不严重。',
        type: 'audio',
        duration: 5,
        timestamp: new Date('2026-01-10T10:16:00'),
      },
      {
        id: 'm4',
        role: 'user',
        content: '好的，体温最高多少度？吃过什么药吗？',
        type: 'audio',
        duration: 4,
        timestamp: new Date('2026-01-10T10:16:45'),
      },
      {
        id: 'm5',
        role: 'aisp',
        content: '昨天晚上量是38.5度，吃了点布洛芬，退了一点，今早又烧起来了。',
        type: 'text',
        timestamp: new Date('2026-01-10T10:17:10'),
      },
    ]
  },
  {
    id: 'eval2',
    studentId: '1',
    caseId: 'case2',
    score: 78,
    communicationScore: 75,
    diagnosisScore: 80,
    treatmentScore: 80,
    feedback: '在与儿童及家长沟通时需要更耐心，问诊思路清晰。',
    timestamp: new Date('2026-01-11T14:20:00'),
    duration: 20,
    messages: [
      {
        id: 'm2-1',
        role: 'aisp',
        content: '医生，我家孩子小明最近老是咳嗽，还有点气喘，都5天了。',
        type: 'text',
        timestamp: new Date('2026-01-11T14:00:00'),
      },
      {
        id: 'm2-2',
        role: 'user',
        content: '家长别急，孩子发烧吗？咳嗽有痰吗？',
        type: 'text',
        timestamp: new Date('2026-01-11T14:00:45'),
      },
      {
        id: 'm2-3',
        role: 'aisp',
        content: '有发烧，前两天39度，现在37.8度左右。咳嗽有痰，听着呼噜呼噜的。',
        type: 'audio',
        duration: 8,
        timestamp: new Date('2026-01-11T14:01:20'),
      },
    ]
  },
  {
    id: 'eval3',
    studentId: '2',
    caseId: 'case1',
    score: 92,
    communicationScore: 95,
    diagnosisScore: 90,
    treatmentScore: 90,
    feedback: '表现优秀，沟通流畅，诊断准确，治疗方案合理。',
    timestamp: new Date('2026-01-12T09:15:00'),
    duration: 12,
  },
];

// 模拟课程任务
export const mockCourseTasks: CourseTask[] = [
  {
    id: 'task1',
    name: '呼吸系统疾病基础训练',
    description: '针对呼吸系统常见疾病的问诊和诊断训练',
    teacherId: '3',
    caseIds: ['case1', 'case2'],
    difficulty: 'easy',
    createdAt: new Date('2026-01-01'),
    assignedStudents: ['1', '2'],
  },
  {
    id: 'task2',
    name: '慢性病管理综合训练',
    description: '高血压、糖尿病等慢性病的沟通和管理',
    teacherId: '3',
    caseIds: ['case3', 'case5'],
    difficulty: 'hard',
    createdAt: new Date('2026-01-05'),
    assignedStudents: ['1'],
  },
];

// 模拟评分标准
export const mockScoringCriteria: ScoringCriteria[] = [
  {
    id: 'criteria1',
    name: '标准评分体系',
    communicationWeight: 0.3,
    diagnosisWeight: 0.4,
    treatmentWeight: 0.3,
    criteria: {
      excellent: '90分以上：沟通流畅，诊断准确，治疗方案完整合理',
      good: '80-89分：沟通良好，诊断基本正确，治疗方案较合理',
      fair: '70-79分：沟通一般，诊断有遗漏，治疗方案不够完善',
      poor: '70分以下：沟通存在问题，诊断错误或遗漏重要信息',
    },
  },
];

// 模拟学习统计数据
export const mockLearningStats: Record<string, LearningStats> = {
  '1': {
    studentId: '1',
    weeklyHours: [2.5, 3, 2, 4, 3.5, 2.8, 3.2], // 最近7周
    semesterHours: 45,
    averageScore: 82,
    completedCases: 12,
    scoreDistribution: {
      excellent: 3,
      good: 6,
      fair: 2,
      poor: 1,
    },
  },
  '2': {
    studentId: '2',
    weeklyHours: [3, 3.5, 4, 3.8, 4.2, 3.5, 4], // 最近7周
    semesterHours: 52,
    averageScore: 88,
    completedCases: 15,
    scoreDistribution: {
      excellent: 8,
      good: 5,
      fair: 2,
      poor: 0,
    },
  },
};

// 模拟知识库数据源
export const mockKnowledgeSources: KnowledgeSource[] = [
  {
    id: 'ks1',
    name: '内部病例库',
    type: 'internal',
    description: '系统内部创建和维护的病例数据',
    status: 'active',
    caseCount: 126,
    category: '综合',
  },
  {
    id: 'ks2',
    name: 'PubMed 医学数据库',
    type: 'external',
    url: 'https://pubmed.ncbi.nlm.nih.gov',
    description: '美国国家医学图书馆维护的生物医学文献数据库',
    status: 'active',
    caseCount: 3500,
    lastSync: new Date('2026-01-14'),
    category: '综合医学',
  },
  {
    id: 'ks3',
    name: '中华医学会病例库',
    type: 'external',
    url: 'https://cma.org.cn',
    description: '中华医学会提供的临床病例数据库',
    status: 'active',
    caseCount: 2800,
    lastSync: new Date('2026-01-13'),
    category: '临床医学',
  },
  {
    id: 'ks4',
    name: 'UpToDate 临床决策支持',
    type: 'external',
    url: 'https://www.uptodate.com',
    apiKey: 'demo_api_key_xxxxx',
    description: '基于循证医学的临床决策支持工具',
    status: 'active',
    caseCount: 1200,
    lastSync: new Date('2026-01-15'),
    category: '临床决策',
  },
  {
    id: 'ks5',
    name: '儿科病例研究数据库',
    type: 'external',
    url: 'https://pediatrics.example.com',
    description: '专注于儿科疾病的临床病例研究',
    status: 'inactive',
    caseCount: 450,
    lastSync: new Date('2025-12-20'),
    category: '儿科',
  },
];

// 模拟知识图谱节点
export const mockKnowledgeNodes: KnowledgeNode[] = [
  {
    id: 'kn1',
    name: '呼吸系统疾病',
    type: 'disease',
    description: '影响呼吸系统的各类疾病',
    relatedNodes: ['kn2', 'kn3', 'kn7'],
    caseCount: 45,
  },
  {
    id: 'kn2',
    name: '上呼吸道感染',
    type: 'disease',
    description: '鼻腔、咽部、喉部的急性炎症',
    relatedNodes: ['kn1', 'kn7', 'kn8', 'kn12'],
    caseCount: 28,
  },
  {
    id: 'kn3',
    name: '支气管炎',
    type: 'disease',
    description: '支气管黏膜及其周围组织的炎症',
    relatedNodes: ['kn1', 'kn8', 'kn9', 'kn13'],
    caseCount: 32,
  },
  {
    id: 'kn4',
    name: '心血管疾病',
    type: 'disease',
    description: '影响心脏和血管系统的疾病',
    relatedNodes: ['kn5', 'kn10', 'kn11'],
    caseCount: 56,
  },
  {
    id: 'kn5',
    name: '高血压',
    type: 'disease',
    description: '以动脉血压持续升高为特征的慢性疾病',
    relatedNodes: ['kn4', 'kn10', 'kn11', 'kn14'],
    caseCount: 42,
  },
  {
    id: 'kn6',
    name: '糖尿病',
    type: 'disease',
    description: '以高血糖为特征的代谢性疾病',
    relatedNodes: ['kn15', 'kn16'],
    caseCount: 38,
  },
  {
    id: 'kn7',
    name: '发热',
    type: 'symptom',
    description: '体温升高超过正常范围',
    relatedNodes: ['kn2', 'kn3', 'kn8'],
    caseCount: 85,
  },
  {
    id: 'kn8',
    name: '咳嗽',
    type: 'symptom',
    description: '呼吸道受刺激引起的防御性反射',
    relatedNodes: ['kn2', 'kn3', 'kn7'],
    caseCount: 76,
  },
  {
    id: 'kn9',
    name: '气促',
    type: 'symptom',
    description: '呼吸困难、呼吸频率加快',
    relatedNodes: ['kn3'],
    caseCount: 42,
  },
  {
    id: 'kn10',
    name: '头晕',
    type: 'symptom',
    description: '头部昏沉不适感',
    relatedNodes: ['kn5', 'kn11'],
    caseCount: 54,
  },
  {
    id: 'kn11',
    name: '头痛',
    type: 'symptom',
    description: '头部疼痛不适',
    relatedNodes: ['kn5', 'kn10'],
    caseCount: 48,
  },
  {
    id: 'kn12',
    name: '对症治疗',
    type: 'treatment',
    description: '针对症状进行缓解性治疗',
    relatedNodes: ['kn2', 'kn13'],
    caseCount: 68,
  },
  {
    id: 'kn13',
    name: '抗感染治疗',
    type: 'treatment',
    description: '使用抗生素或抗病毒药物治疗感染',
    relatedNodes: ['kn2', 'kn3', 'kn12'],
    caseCount: 52,
  },
  {
    id: 'kn14',
    name: '降压治疗',
    type: 'treatment',
    description: '使用药物降低血压',
    relatedNodes: ['kn5'],
    caseCount: 42,
  },
  {
    id: 'kn15',
    name: '内科',
    type: 'department',
    description: '内科疾病诊疗',
    relatedNodes: ['kn1', 'kn2', 'kn4', 'kn5', 'kn6'],
    caseCount: 95,
  },
  {
    id: 'kn16',
    name: '儿科',
    type: 'department',
    description: '儿童疾病诊疗',
    relatedNodes: ['kn3'],
    caseCount: 48,
  },
];